---
- hosts: rhel
  become: true
  tasks:
  - name: copy files from one source to another
    copy:
      src: "{{ src }}"
      dest: "{{ dest }}"
      owner: reuben
      group: reuben
      mode: 0755
      remote_src: yes
