---
- hosts: debian
  become: true
  tasks:
  - name: check if server needs a reboot
    stat:
      path: /run/reboot-required
    register: stat_result
  - name: if true reboot server
    reboot:
    when: stat_result.stat.exists == True
